### ISSUE TITLE
Link back to your article

### ISSUE THREAD

**Issue by schollii** [sashee/terraform_manage_lambda_logs#1]
Hi, that's a nice article you wrote at https://advancedweb.hu/how-to-manage-lambda-log-groups-with-terraform/, your readme should link back to it. 

BTW I got here because I could not see a way of "liking" the article at that link. Starring it works for me :)

**Comment by sashee** [comment]
Hey, glad it's useful for you! Indeed, the GitHub page missed a link. I added one in the about part, so I think we can close this ticket:)
